# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_ui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1440, 789)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.view_program_1 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.view_program_1.setGeometry(QtCore.QRect(25, 150, 331, 391))
        self.view_program_1.setReadOnly(True)
        self.view_program_1.setObjectName("view_program_1")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(26, 126, 91, 16))
        self.label.setObjectName("label")
        self.choose_file_1 = QtWidgets.QPushButton(self.centralwidget)
        self.choose_file_1.setGeometry(QtCore.QRect(235, 66, 111, 32))
        self.choose_file_1.setObjectName("choose_file_1")
        self.result_1 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.result_1.setGeometry(QtCore.QRect(25, 570, 331, 151))
        self.result_1.setReadOnly(True)
        self.result_1.setObjectName("result_1")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(144, 1, 81, 31))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(27, 550, 81, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(25, 72, 41, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(25, 100, 91, 16))
        self.label_5.setObjectName("label_5")
        self.program_lang_1 = QtWidgets.QComboBox(self.centralwidget)
        self.program_lang_1.setGeometry(QtCore.QRect(91, 94, 151, 32))
        self.program_lang_1.setObjectName("program_lang_1")
        self.program_lang_1.addItem("")
        self.file_dir_1 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.file_dir_1.setGeometry(QtCore.QRect(65, 70, 171, 21))
        self.file_dir_1.setReadOnly(True)
        self.file_dir_1.setObjectName("file_dir_1")
        self.view_problem_1 = QtWidgets.QPushButton(self.centralwidget)
        self.view_problem_1.setGeometry(QtCore.QRect(125, 34, 111, 32))
        self.view_problem_1.setObjectName("view_problem_1")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(494, 1, 81, 31))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(375, 100, 91, 16))
        self.label_7.setObjectName("label_7")
        self.result_2 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.result_2.setGeometry(QtCore.QRect(375, 570, 331, 151))
        self.result_2.setReadOnly(True)
        self.result_2.setObjectName("result_2")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(377, 550, 81, 16))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(376, 126, 91, 16))
        self.label_9.setObjectName("label_9")
        self.view_program_2 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.view_program_2.setGeometry(QtCore.QRect(375, 150, 331, 391))
        self.view_program_2.setReadOnly(True)
        self.view_program_2.setObjectName("view_program_2")
        self.choose_file_2 = QtWidgets.QPushButton(self.centralwidget)
        self.choose_file_2.setGeometry(QtCore.QRect(585, 66, 111, 32))
        self.choose_file_2.setObjectName("choose_file_2")
        self.program_lang_2 = QtWidgets.QComboBox(self.centralwidget)
        self.program_lang_2.setGeometry(QtCore.QRect(441, 94, 151, 32))
        self.program_lang_2.setObjectName("program_lang_2")
        self.program_lang_2.addItem("")
        self.view_problem_2 = QtWidgets.QPushButton(self.centralwidget)
        self.view_problem_2.setGeometry(QtCore.QRect(475, 34, 111, 32))
        self.view_problem_2.setObjectName("view_problem_2")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(375, 72, 41, 16))
        self.label_10.setObjectName("label_10")
        self.file_dir_2 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.file_dir_2.setGeometry(QtCore.QRect(415, 70, 171, 21))
        self.file_dir_2.setReadOnly(True)
        self.file_dir_2.setObjectName("file_dir_2")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(844, 1, 81, 31))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(725, 100, 91, 16))
        self.label_12.setObjectName("label_12")
        self.result_3 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.result_3.setGeometry(QtCore.QRect(725, 570, 331, 151))
        self.result_3.setReadOnly(True)
        self.result_3.setObjectName("result_3")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(727, 550, 81, 16))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(726, 126, 91, 16))
        self.label_14.setObjectName("label_14")
        self.view_program_3 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.view_program_3.setGeometry(QtCore.QRect(725, 150, 331, 391))
        self.view_program_3.setReadOnly(True)
        self.view_program_3.setObjectName("view_program_3")
        self.choose_file_3 = QtWidgets.QPushButton(self.centralwidget)
        self.choose_file_3.setGeometry(QtCore.QRect(935, 66, 111, 32))
        self.choose_file_3.setObjectName("choose_file_3")
        self.program_lang_3 = QtWidgets.QComboBox(self.centralwidget)
        self.program_lang_3.setGeometry(QtCore.QRect(791, 94, 151, 32))
        self.program_lang_3.setObjectName("program_lang_3")
        self.program_lang_3.addItem("")
        self.view_problem_3 = QtWidgets.QPushButton(self.centralwidget)
        self.view_problem_3.setGeometry(QtCore.QRect(825, 34, 111, 32))
        self.view_problem_3.setObjectName("view_problem_3")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(725, 72, 41, 16))
        self.label_15.setObjectName("label_15")
        self.file_dir_3 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.file_dir_3.setGeometry(QtCore.QRect(765, 70, 171, 21))
        self.file_dir_3.setReadOnly(True)
        self.file_dir_3.setObjectName("file_dir_3")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(1194, 1, 81, 31))
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(1075, 100, 91, 16))
        self.label_17.setObjectName("label_17")
        self.result_4 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.result_4.setGeometry(QtCore.QRect(1075, 570, 331, 151))
        self.result_4.setReadOnly(True)
        self.result_4.setObjectName("result_4")
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(1077, 550, 81, 16))
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.centralwidget)
        self.label_19.setGeometry(QtCore.QRect(1076, 126, 91, 16))
        self.label_19.setObjectName("label_19")
        self.view_program_4 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.view_program_4.setGeometry(QtCore.QRect(1075, 150, 331, 391))
        self.view_program_4.setReadOnly(True)
        self.view_program_4.setObjectName("view_program_4")
        self.choose_file_4 = QtWidgets.QPushButton(self.centralwidget)
        self.choose_file_4.setGeometry(QtCore.QRect(1285, 66, 111, 32))
        self.choose_file_4.setObjectName("choose_file_4")
        self.program_lang_4 = QtWidgets.QComboBox(self.centralwidget)
        self.program_lang_4.setGeometry(QtCore.QRect(1141, 94, 151, 32))
        self.program_lang_4.setObjectName("program_lang_4")
        self.program_lang_4.addItem("")
        self.view_problem_4 = QtWidgets.QPushButton(self.centralwidget)
        self.view_problem_4.setGeometry(QtCore.QRect(1175, 34, 111, 32))
        self.view_problem_4.setObjectName("view_problem_4")
        self.label_20 = QtWidgets.QLabel(self.centralwidget)
        self.label_20.setGeometry(QtCore.QRect(1075, 72, 41, 16))
        self.label_20.setObjectName("label_20")
        self.file_dir_4 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.file_dir_4.setGeometry(QtCore.QRect(1115, 70, 171, 21))
        self.file_dir_4.setReadOnly(True)
        self.file_dir_4.setObjectName("file_dir_4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1440, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setBaseSize(QtCore.QSize(0, 0))
        self.toolBar.setAutoFillBackground(False)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "程式碼預覽："))
        self.choose_file_1.setText(_translate("MainWindow", "選擇檔案"))
        self.label_2.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:24pt;\">第一題</span></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:24pt;\">第一題</span></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "測試結果："))
        self.label_4.setText(_translate("MainWindow", "檔案 ："))
        self.label_5.setText(_translate("MainWindow", "程式語言："))
        self.program_lang_1.setItemText(0, _translate("MainWindow", "C++"))
        self.view_problem_1.setText(_translate("MainWindow", "看題目"))
        self.label_6.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:24pt;\">第一題</span></p></body></html>"))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:24pt;\">第二題</span></p></body></html>"))
        self.label_7.setText(_translate("MainWindow", "程式語言："))
        self.label_8.setText(_translate("MainWindow", "測試結果："))
        self.label_9.setText(_translate("MainWindow", "程式碼預覽："))
        self.choose_file_2.setText(_translate("MainWindow", "選擇檔案"))
        self.program_lang_2.setItemText(0, _translate("MainWindow", "C++"))
        self.view_problem_2.setText(_translate("MainWindow", "看題目"))
        self.label_10.setText(_translate("MainWindow", "檔案 ："))
        self.label_11.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:24pt;\">第一題</span></p></body></html>"))
        self.label_11.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:24pt;\">第三題</span></p></body></html>"))
        self.label_12.setText(_translate("MainWindow", "程式語言："))
        self.label_13.setText(_translate("MainWindow", "測試結果："))
        self.label_14.setText(_translate("MainWindow", "程式碼預覽："))
        self.choose_file_3.setText(_translate("MainWindow", "選擇檔案"))
        self.program_lang_3.setItemText(0, _translate("MainWindow", "C++"))
        self.view_problem_3.setText(_translate("MainWindow", "看題目"))
        self.label_15.setText(_translate("MainWindow", "檔案 ："))
        self.label_16.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:24pt;\">第一題</span></p></body></html>"))
        self.label_16.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:24pt;\">第四題</span></p></body></html>"))
        self.label_17.setText(_translate("MainWindow", "程式語言："))
        self.label_18.setText(_translate("MainWindow", "測試結果："))
        self.label_19.setText(_translate("MainWindow", "程式碼預覽："))
        self.choose_file_4.setText(_translate("MainWindow", "選擇檔案"))
        self.program_lang_4.setItemText(0, _translate("MainWindow", "C++"))
        self.view_problem_4.setText(_translate("MainWindow", "看題目"))
        self.label_20.setText(_translate("MainWindow", "檔案 ："))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))

